$:
  vscode:
    - runner:
        cpus: 3
      docker:
        image: docker.cnb.cool/shynur/ide
      services:
        - vscode
      stages:
        - name: restore packed volume
          script: |
            if [ $SHYNUR_IDE_PACKED_VOLUME ]; then
              pack-vol-of-shynur-ide.bash SHYNUR_IDE_PACKED_VOLUME
            else
              echo "SHYNUR_IDE_PACKED_VOLUME 未注入, 跳过解包" >&2
            fi
        - name: launch shynur-ide
          script: |
            rm -f ~/.gitconfig
            setsid launch-this-ide.bash </dev/null &>/var/log/shynur-ide-launch.log &
